name: Two
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  User:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Date print
        run: whoami
        shell: bash
  
  WorkingDir:
    runs-on: ubuntu-latest
    steps:
      - name: Working Dir Print
        run: pwd
        shell: bash
    