name: Two
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

  jobs:
    Sum:
      runs-on: ubuntu-latest
      steps:
        - uses: action/checkout@v4
        - name: Date print
          run: echo date
          shell: bash
    